apiVersion: v1
description: A Helm chart for Kubernetes EventStore.
name: eventstore
home: https://eventstore.com/
version: 0.1.3
appVersion: 5.0.10
keywords:
  - eventstore
sources:
  - https://github.com/EventStore/eventstore-docker
  - https://github.com/EventStore/EventStore
maintainers:
  - name: riccardone
    email: riccardo.dinuzzo@yahoo.com
icon: https://eventstore.org/images/ouro-full.svg
